name: Update SSM Parameter

on:
  workflow_dispatch:
    inputs:
      service_name:
        description: 'Service name'
        required: true
        default: ''
      service_version:
        description: 'Service version'
        required: false
        default: ''
      env_type:
        description: 'Environment type'
        required: true
        default: ''
      aws_region:
        description: 'AWS region'
        required: true
        default: ''
      aws_account:
        description: 'AWS account'
        required: true
        default: ''

jobs:
  update-ssm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/terraform-role
          role-session-name: aws-role
          aws-region: eu-west-1

      - name: Setup Variables
        id: setup-vars
        run: |
          echo "envType=${{ github.event.inputs.env_type }}" >> $GITHUB_ENV
          echo "serviceVersion=${{ github.event.inputs.service_version }}" >> $GITHUB_ENV
          echo "serviceName=${{ github.event.inputs.service_name }}" >> $GITHUB_ENV
          echo "tf_workspace=${{ github.event.inputs.env_type }}" >> $GITHUB_ENV
          echo "awsRegion=${{ github.event.inputs.aws_region }}" >> $GITHUB_ENV
          echo "awsAccount=${{ github.event.inputs.aws_account }}" >> $GITHUB_ENV

      - name: Update SSM Parameter
        if: ${{ env.serviceVersion != '' }}
        run: |
          echo "Service version is ${{ env.serviceVersion }} so updating existing value"
          aws ssm put-parameter --region ${{ env.awsRegion }} --overwrite --name /baseballinfra/${{ env.envType }}/${{ env.serviceName }} --value ${{ env.serviceVersion }} --type String